### ISSUE TITLE
Unable to install because requires beta version

### ISSUE THREAD

**Issue by damccull** [foundry-vtt-community/macros#145]
Issue: Users will be unable to install this module or update it because it requires a version that is currently beta. Users should not be required to install a beta version of FoundryVTT to install or update this plugin.

Solution: Move development of the plugin to a branch and change the manifest file's update source to point at the branch's manifest. Then when the new version of FoundryVTT is released, update the manifest file's source to point at the master branch again, and merge the updated plugin into master.

This will allow installs on current stable versions of FoundryVTT while still allowing for development on the beta track.

A workaround is available: Users can point their install path to the tagged older version that corresponds to their installed FoundryVTT version, which will let it install. Since the manifest at that version still points to master, when they click update they will get an error about requiring the beta version, but it will stay installed without updating. Then when they install a beta (or new release) of FoundryVTT, it will update normally.

However, again, users should not have to use this workaround or be subjected to beta software to use the plugin.

**Comment by AnthonyVadala** [comment]
I have released a new version of the module (v0.27) with support for the latest release of Foundry VTT v0.6.6.

As all macros are use at your own risk, I think moving forward keeping the `minimumCoreVersion` as the latest release and the `compatibleCoreVersion` as the latest beta release should be a good enough solution for now.
