### ISSUE TITLE
k is not defined

### ISSUE THREAD

**Issue by pillarsdotnet** [foundry-vtt-community/macros#149]
When checking for updates ini Foundry VTT core 0.75, I get a popup saying "k is not defined".

![image](https://user-images.githubusercontent.com/173180/97786045-2924b480-1b7f-11eb-9ddb-99e77b11cd31.png)

**Comment by Merudo** [comment]
Uninstalling and reinstalling the module fixed it for me.

**Comment by pillarsdotnet** [comment]
Yeah, did for me, too. I had to paste the URL from github, though.
