### ISSUE TITLE
Divine Smite doesn't work on 7.5

### ISSUE THREAD

**Issue by Signorini** [foundry-vtt-community/macros#155]
Divine smite are throwing following error `There was an error in your macro syntax. See the console (F12) for details`

```
SyntaxError: Illegal return statement
    at Macro.execute (foundry.js:32357)
    at Hotbar._onClickMacro (foundry.js:20282)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
```

Foundry VTT 7.5
Macros versions 0.27

Checking, why the macro doesn't work.

**Comment by Merudo** [comment]
Can't reproduce. It works fine on my end.

**Comment by AnthonyVadala** [comment]
Unable to reproduce bug in Foundry VTT 0.7.9 using updated Divine Smite from #157
