### ISSUE TITLE
Suggestion: make this into a compendium

### ISSUE THREAD

**Issue by kakaroto** [foundry-vtt-community/macros#16]
I think having this repo be a 'community macros' module with all the macros importable from a compendium would make it much more approachable for people.
Don't know if you agree, but that's my suggestion.

**Comment by AnthonyVadala** [comment]
I like this idea!

**Comment by AnthonyVadala** [comment]
Done!

Just need to come up with a hopefully automated way to handle adding new macros in the future. Adding directly to the .db files seems to cause corruption issues.

**Comment by shawndibble** [comment]
Is it possible to request my name not be assigned next to macros? I don't mind it in the github history, but having it shown in game is something I would prefer not to have.

**Comment by AnthonyVadala** [comment]
> 
> 
> Is it possible to request my name not be assigned next to macros? I don't mind it in the github history, but having it shown in game is something I would prefer not to have.

I am going to remove names from the macros, as I was doing them based off the commit name, but some were added on behalf of someone from the Discord. 

Plus it will make the names cleaner in the compendium.

**Comment by AnthonyVadala** [comment]
@shawndibble names have been removed from macros as of v0.3

**Comment by shawndibble** [comment]
may want to look into github actions that can automatically create the .db files after a merge.

**Comment by AnthonyVadala** [comment]
> may want to look into github actions that can automatically create the .db files after a merge.

It is something on my radar and would make management of the packs WAY easier, but as of right now directly entering data into a `.db` file causes a bunch of data corruption errors in the debug log of Foundry.

So once a better method of editing `.db` files becomes available I'll be all over it!
