### ISSUE TITLE
Hunter's Mark CUB

### ISSUE THREAD

**Issue by atleticano-snp** [foundry-vtt-community/macros#163]
Hi

Hunter's Mark macros was not properly applying the CUB condition.
It seems that them problem in line 12 in GMConditions

game.cub.**apply**Condition(condition, target, {warn: true}); <- Syxtax error

game.cub.**add**Condition(condition, target, {warn: true}); <- worked here

**Comment by AnthonyVadala** [comment]
This appears to be work using the instructions added in commit 44705ebe84f703f0d0a975f03d68e33e3c06184e
