### ISSUE TITLE
Guidance adding 1d4 twice to Skill checks (5e)

### ISSUE THREAD

**Issue by Chaithi** [foundry-vtt-community/macros#172]
**Foundry Version**: 0.7.9
**Module Version**: 0.33

When using the "Guidance" macro on an actor, it correctly responds the chat message and correctly adds the +1d4 on Ability checks. However, on Skill checks, it adds +1d4 twice.

Thinking it may be an issue with other modules, I deactivated all modules except this one. Issue persists. I reviewed the code and I can't see where it's going wrong...
![bug](https://user-images.githubusercontent.com/6610999/105517148-4e1b5600-5c9c-11eb-9acf-63017ac328ad.png)

**Comment by Kayne** [comment]
Hi,

I have resolved this issue with simple fix in macro code. I added #175 pull request with fix and explanation, what was wrong. You may just edit the macro yourself in your game world or wait for approval of my pull request :)
