### ISSUE TITLE
Contribute Pathfinder 2e Macros to the Module

### ISSUE THREAD

**Issue by AdamantiteAdventurer** [foundry-vtt-community/macros#174]
Hello! I didn't see an option to contact you directly, so I figured this would do. However, I have like 40 something macros I would like to contribute to the Module that I either wrote myself or had help from the original creators (who okay'd the sharing to the community). 

https://github.com/AdamantiteAdventurer/fvtt-macros-pf2e

**Comment by AnthonyVadala** [comment]
Hey! I will get those macros added in the next module update!

**Comment by AdamantiteAdventurer** [comment]
Not sure if it's preferred or not, but here are the same scripts with images for the icons:
https://github.com/AdamantiteAdventurer/fvtt-macros-pf2e/tree/JSONs_with_Images

**Comment by AdamantiteAdventurer** [comment]
Apparently, I don't know how Github works lol, they are all in the same folder.

**Comment by AnthonyVadala** [comment]
All of these macros have been added in version 0.34!
