### ISSUE TITLE
Token Vision Configuration macro is blinding when using Light (Cantrip)

### ISSUE THREAD

**Issue by ajclarke90** [foundry-vtt-community/macros#178]
I suspect this is because there is no alpha, so foundry is drawing 100% white light around the token, but it's blinding. 

![image](https://user-images.githubusercontent.com/4687383/107856812-b0422380-6e22-11eb-9c05-8c603f6585be.png)

I fixed it by changing Light to the following: 

`          case "light":
            dimLight = 40;
            brightLight = 20;
            lightAnimation = {type: "none"};
            lightColor = colorWhite;
            lightAlpha = 0.15
            break;`

**Comment by AnthonyVadala** [comment]
This change has been added in v0.35
