### ISSUE TITLE
Roll token HP macro needs update

### ISSUE THREAD

**Issue by szefo09** [foundry-vtt-community/macros#204]
https://github.com/foundry-vtt-community/macros/blob/121ddf908e7426019557b0d7b04bf2f8b94f543a/roll/token_hp.js#L23-L26

Those lines of code do only assign the values, but do not actually update the token, so the newly rolled HP isn't applied.
This could be fixed by changing Line 23 and 24 into `actor.update({"data.attributes.hp.value": hp, "data.attributes.hp.max": hp});`  with await for the printMessage function to not fire before the changes apply.

**Comment by AnthonyVadala** [comment]
This has been changed in version 0.41
