### ISSUE TITLE
Accurate Module/Core Version

### ISSUE THREAD

**Issue by tjlanza** [foundry-vtt-community/macros#207]
While many of the macros within this module are technically compatible with 0.8, a suspect a significant portion are only compatible by virtue of the deprecation paths built into the software - i.e. they're not really compatible, they're just shimmed. In fact, there are some seemingly simple macros, e.g. "Close All Doors" written by Atropos himself, that do not function at all in 0.8.

I think its disingenuous to indicate compatibility when the individual macros within the module have not be verified and updated to use 0.8 functions. This module has gone from a source of examples for how Foundry does things to a collection of examples of how Foundry *used to do* things.

I'm not certain of the right path forward. My only horse in the race is that of a user, not a developer or contributor. My preference would be for this module's 0.7.10-compatible state to be forked (for archive purposes), then any macro not using the full 0.8 API to be removed until it it does use 0.8 functions.

**Comment by AnthonyVadala** [comment]
Thank you for your suggestions!

I have created a new issue (#208) to track macro compatibility and an [archived repo](https://github.com/foundry-vtt-community/macros-0.7.X) for a 0.7.X compatible module.
