### ISSUE TITLE
Light Picker Color seems to be broken.

### ISSUE THREAD

**Issue by justinthejaguar** [foundry-vtt-community/macros#211]
Trying to use the Light Picker Color macro OOB. It seems to be missing some data.

![image](https://user-images.githubusercontent.com/38022481/121391976-f31d8f00-c91c-11eb-9abb-50b1ed478a91.png)

![image](https://user-images.githubusercontent.com/38022481/121392059-07618c00-c91d-11eb-98a0-dbdd20e17673.png)

**Comment by ravingdragoon** [comment]
I have the same issue, however it seems to snag on different lines of the code.

foundry.js:8865  
Error: [YPA6Gv5DFNmggmVo] TokenData lightAlpha "0.25" is not a number between 0 and 1  
    at TokenData._validateField (data.mjs:382)  
    at TokenData.validate (data.mjs:273)  
    at BabeleClientDatabaseBackend._preUpdateDocumentArray (foundry.js:8862)  
    at BabeleClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8824)  
    at BabeleClientDatabaseBackend.update (backend.mjs:153)  
    at async Function.updateDocuments (document.mjs:366)  
    at async TokenDocument5e.update (document.mjs:448)  
_preUpdateDocumentArray @ foundry.js:8865  
_updateEmbeddedDocuments @ foundry.js:8824  
update @ backend.mjs:153  
async function (async)  
update @ backend.mjs:151  
updateDocuments @ document.mjs:366  
update @ document.mjs:448  
update @ foundry.js:19458  
eval @ VM37022:6  
tokenUpdate @ VM37022:6  
callback @ VM37022:57  
submit @ foundry.js:20673  
_onClickButton @ foundry.js:20636  
dispatch @ jquery.min.js:2  
v.handle @ jquery.min.js:2

**Comment by Preposthumous** [comment]
It took me a while of reading docs to figure it out, but I think I kinda understand what's wrong - at least, well enough to make it work:

The .val jQuery method on line 51 is pulling the value from the dialog's slider as a string, not a number. The jQuery documentation for the .val method says it can return a string, a number, or an array, but it seems to default to strings and only returns numbers when something something "valHooks" something? I'm not clear on whether there's something that could be changed on lines 75-76 in the html section to make this work, but changing line 51 to
`                const newAlpha = parseFloat(html.find("#alpha").val());`
fixed it for me.

I'm still learning the most basic aspects of using git to manage code, so please accept my apologies for not using the built in mechanisms to edit this code myself and suggest a merge. I don't really know how that all works, yet.
