### ISSUE TITLE
Shield Equip Unequip Macro Broken

### ISSUE THREAD

**Issue by Bryn1701** [foundry-vtt-community/macros#218]
I am on Foundry 0.8.6 and D&D 1.3.3 and when I use the Shield Equip Unequip macro it kicks up a lot of errors, both unequip and equip. It seems to work fine, until you refresh after using this macro and the token it was used on becomes un selectable and you need to delete the token and pull a new one out from the sidebar. 

The error in question was...
jquery.min.js:2 Uncaught (in promise) Error: Syntax error, unrecognized expression: Ranunculus <b>equips</b> their <i> Shield</i>
    at Function.se.error (jquery.min.js:2)
    at se.tokenize (jquery.min.js:2)
    at se.select (jquery.min.js:2)
    at Function.se [as find] (jquery.min.js:2)
    at S.fn.init.find (jquery.min.js:2)
    at new S.fn.init (jquery.min.js:2)
    at S (jquery.min.js:2)
    at new Dnd5Handler (dnd5-handler.js:3)
    at specialCaseAnimations (autoAnimations.js:453)
    at autoAnimations.js:280

**Comment by mainframe97** [comment]
Hello Bryn,

I tried the macro too, and while the same error popped out, the token was fine even after several try or refresh.

Moreover the intended effect of the macro seems to work too (the shield gets Un/Equipped).

Maybe it's a module you have activated that tries to place an effect on items (like DAE SRD or CUB)?

**Comment by Bryn1701** [comment]
Could be. Never had a macro do that before. I do indeed have DAE and Cub installed

**Comment by AnthonyVadala** [comment]
This macro has been updated in the v9 branch of this module.
