### ISSUE TITLE
The macro "Close All Doors" doesn't work anymore

### ISSUE THREAD

**Issue by Majea** [foundry-vtt-community/macros#219]
Foundry version: 0.8.7
Community macros version: 0.42.0 

The doors do not close anymore. It doesn't seem to have any effect. I have tried on a fresh world with no active module and I had the same result.

I've tried to fix the deprecation reported in the logs, but I didn't get more success. Here is what I tried: 
```
canvas.scene.updateEmbeddedDocuments("Wall", canvas.scene.data.walls.map(w => {
  return {_id: w.id, ds: w.ds === 1 ? 0 : w.ds};
})); 
```

**Comment by mainframe97** [comment]
Try the following:

```
var doors = canvas.walls.placeables.filter(wall => wall.data.door);

var updates = doors.map(door => { return { _id: door.id, ds: door.data.ds === 1 ? 0 : door.data.ds } });

canvas.walls.updateMany(updates);
```

I tested it in 0.8.7 and it worked.

**Comment by Majea** [comment]
ok, thanks. That one works. I'll try pushing a PR later today.
