### ISSUE TITLE
FVTT 0.8.7 - "Create Chat Message" macro missing vital line

### ISSUE THREAD

**Issue by buttonpushertv** [foundry-vtt-community/macros#222]
As it exists in FVTT Community Macros v.0.42.0, the "Create Chat Message" macro does not work without the addition of this line at the top of the macro:

`let controlledToken = canvas.tokens.controlled[0];`

Running in FVTT 0.8.7 (node.,js install)

**Comment by AnthonyVadala** [comment]
Added line with commit [dae877d](https://github.com/foundry-vtt-community/macros/commit/dae877d8c5f2b0c653d37bb9470f63d2934c515a#diff-b35994afbc02757b2ccf0a39db07c482d4b83da258fa6d0711e3308fa76147f2)
