### ISSUE TITLE
Quite a few macros no longer function

### ISSUE THREAD

**Issue by GambetTV** [foundry-vtt-community/macros#225]
I think since updating to 0.8 a lot of macros need to be updated. "Tile Toggle Hidden Status" for instance is broken.

**Comment by AnthonyVadala** [comment]
Macros are currently being updated for the newly released v9 of Foundry VTT. The macro that you mentioned is one of the ones that has been updated.

Progress on macros being updated can be found [here](https://github.com/orgs/foundry-vtt-community/projects/2).
