### ISSUE TITLE
using the "Folder Permission" macro and can't get it to work properly.

### ISSUE THREAD

**Issue by eyalhaim1** [foundry-vtt-community/macros#245]
using this macro on a folder of journal entries that are divided by subfolders, getting the next error:
![image](https://user-images.githubusercontent.com/91762509/137183887-0e70f5cc-0a41-4c48-a71c-4b00589b5c1a.png)
"JournalEntryData permission "[object object]" is not mapping of user ID's and document permission levels"

THANK YOU!!

**Comment by AnthonyVadala** [comment]
This has been fixed in merged pull request #272
