### ISSUE TITLE
Removal of PF2e macros

### ISSUE THREAD

**Issue by TMunsie** [foundry-vtt-community/macros#250]
Please remove the PF2e macros from this module. 

At present, they have not been maintained and either have been replaced by core functionality in the PF2e system or are incompatible with documents as introduced in Foundry 0.8 requiring JSON actor editing.

**Comment by AnthonyVadala** [comment]
Macros that have been rolled into the core PF2E system will be removed once a Foundry VTT v9 compatible version of this module is released.

You can check on the status of the v9 compatibility project [here](https://github.com/orgs/foundry-vtt-community/projects/2)
Also you check out the v9 development branch [here](https://github.com/foundry-vtt-community/macros/tree/v9)
