### ISSUE TITLE
Need "Light Picker" macro(s?) updated to v9

### ISSUE THREAD

**Issue by Battenhatch** [foundry-vtt-community/macros#251]
As the title says. The Light Picker macro is very useful to me, but does not function under v9, and I have exctly zero skills when it comes to making such thing work.

**Comment by OfficerHalf** [comment]
@Battenhatch raised a PR for an updated macro: #253 
In the meantime, copy and modify at your leisure.

**Comment by AnthonyVadala** [comment]
PR #253 has been merged into the v9 development branch of the module.
