### ISSUE TITLE
none of my macros work since updating to v9

### ISSUE THREAD

**Issue by friction1** [foundry-vtt-community/macros#276]
none of my macros work since updating to v9

attempting to use delete spell templates and bless/guidance for D&D5E

**Comment by AnthonyVadala** [comment]
Hello! All three of these macros have updated for the v9.5 release of the module. Please check for an update on your Foundry VTT instance.

 #259 updated `delete_all_templates.js`
 #275 updated `bane.js`/`guidance.js`
