### ISSUE TITLE
Incorrect macro update

### ISSUE THREAD

**Issue by kandashi** [foundry-vtt-community/macros#279]
https://github.com/foundry-vtt-community/macros/blob/main/token/randomize_wildcard_tokens.js
this macro was "updated" with the wrong script

**Comment by kandashi** [comment]
for(let nextToken of canvas.tokens.placeables) {
    if (nextToken.actor.data.token.randomImg) {
        let tokenImgArray = await game.actors.get(nextToken.actor.id).getTokenImages();
        let imageChoice = Math.floor(Math.random() * tokenImgArray.length);
        let image = tokenImgArray[imageChoice]
        await nextToken.document.update({ "img": image })
    }
}
this is the "correct" update for v9 compatibility

**Comment by AnthonyVadala** [comment]
Sorry about that. This has been corrected in the v9.7 release.
