### ISSUE TITLE
Shrink or Enlarge Token Macro

### ISSUE THREAD

**Issue by Stove8795** [foundry-vtt-community/macros#282]
![Screenshot 2022-01-23 113822](https://user-images.githubusercontent.com/98275652/150688508-a3fa09ca-64b5-499b-9d2a-4617b1828bb4.png)

When I try out the shrink or enlarge macro I keep getting this syntax error

**Comment by aco-rt** [comment]
I just replaced the last line, from
`canvas.tokens.updateMany(updates);`
to 
`canvas.scene.updateEmbeddedDocuments("Token", updates);`
And it works

**Comment by AnthonyVadala** [comment]
This has been updated in v9.9
