### ISSUE TITLE
PF2E Blood Magic Proc not functional

### ISSUE THREAD

**Issue by jocolamarco** [foundry-vtt-community/macros#289]
It seems to create a new icon and condition, not following the system implementation.

Example for Draconic Blood Magic:

1. Does not change AC
2. Doesn't expire properly

The PF2e system already has blood magic effects that can be dragged to the token to activate, it can also be activated via TAH or Character Sheet, working properly.

It also doesn't cover all bloodlines available.

**Comment by AnthonyVadala** [comment]
This macro has been removed in v9.9
