### ISSUE TITLE
Delete all Templates and Create Ambient Light not working in v9

### ISSUE THREAD

**Issue by SwordofSpirit** [foundry-vtt-community/macros#297]
I've noticed these two didn't make the change to v9 (the author of the light one actually contributed the updated version, but it somehow didn't get put in the package).

I'm assuming there was some break down in communicating all the changes and such, but I just wanted to make whomever it concerns aware that these ones in particular do not function, and I expect probably others slipped through the cracks.

**Comment by AnthonyVadala** [comment]
Sorry about that. These macros have been updated in v9.10

Please feel free report if you find any more macros that slipped through the cracks.
