### ISSUE TITLE
Max NPC HP 

### ISSUE THREAD

**Issue by mattimeo84** [foundry-vtt-community/macros#298]
I imported the macro,executed it, and received an error message.

"There was an error in your macro syntax. See the console (F12) for details."

![image](https://user-images.githubusercontent.com/83080745/153459556-e194af1d-4575-42ff-8122-93c58562c676.png)

**Comment by kaelad02** [comment]
I was going to update this but it doesn't work in the dnd5e system. I fixed the reported error but ran into another issue with how it gets attributes. I tried looking through the commit history but can't figure out what system this was designed for. It looks like it will work for dnd5e but I wanted to be sure.
If we can't tell, I can just update it for dnd5e and get it working.
