### ISSUE TITLE
remove pf2e macros

### ISSUE THREAD

**Issue by Drental** [foundry-vtt-community/macros#309]
The pf2e macros are outdated and breaking newer people's characters. Can you please remove them?

The system evolves faster than the macros can and the number of macros in this module is too large to be picked up by any developer who has good system knowledge.

this is causing us supporters frustration because the support cases are entirely preventable and the users have a bad first experience with FVTT that they really don't need. Thank you in advance.

**Comment by Drental** [comment]
then to adress the ones that are actively damaging actors and can only be fixed by exporting and json surgery (as we like to call it)

any macro that contains "customModifiers" (or "addCustomModifier") is actively harmful, can you grep and remove those? If you give me the list I can make sure that all of them are already replaced by the system if that helps your peace of mind.

The short list I notice at a glance are:

- animal Rage
- Dueling Cape
- Dueling Parry
- fury instinct rage
- gozreh Sickness 
- inspire Courage
- parry
- premonition of avoidance
- rain of embers stance
- terrifying resistance
- probably more, but I went off from a glance at the names and a short check inside the suspicious ones.

Thank you!

**Comment by AnthonyVadala** [comment]
@Drental @jocolamarco sorry for the delayed response, every nonworking and broken macro from every system has now been removed from their respective system compendium and placed in a new directory called `archived` as of update v9.13

All current open issues have also been re-tagged and a new pinned issue has been created to track all user reported macro issues outside of the GitHub project board.
