### ISSUE TITLE
Chartopia pull macro doesn't work in 0.9.x series of Foundry

### ISSUE THREAD

**Issue by tbrockwood** [foundry-vtt-community/macros#327]
Just tried to use this and it fails on my version 0.9x foundry. Looks like it was last updated back in the 0.8.x. days. Any chance of an update? Or is there a setting I can change to enable it?

Here's the console error

Access to XMLHttpRequest at 'https://chartopia.d12dev.com/test/dice-roll-result?chart_id=34303' from origin 'https://servername.moltenhosting.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mattstjean** [comment]
@tbrockwood I just ran into this issue and fixed it myself, don't have time to do a PR though so I am sharing here.

```
/**
 * Make a roll from chartopia and output the results in the chat window.
 * If you find yourself using this macro often, please support chartopia on patreon.
 */

// chart id from url. IE 19449 is the chart id in https://chartopia.d12dev.com/chart/19449/
const chartId = 61778;
// only let the gm see the results. false = everyone sees in chat. true = gm whispered results.
const gmOnly = false;


//////////////////////////////////
/// Don't edit past this point ///
//////////////////////////////////

const requestUrl = `https://chartopia.d12dev.com/api/charts/${chartId}/roll/`;


function roll(id) {
  let request = new XMLHttpRequest();
  request.open('POST', requestUrl, true);

  request.onload = function() {
    if (request.status >= 200 && request.status < 400) {
      // Success!
      let whisper = !!gmOnly ? game.users.map(u => {
          if (u.isGM) return u.id;
      }) : [];
      console.log('whisper', whisper);
      // Create chat content.
      const response = JSON.parse(request.response);
      let resultsList = ``;
      if (Array.isArray(response.results)) {
        response.results.forEach(result => {
            result = result.replace("**", "<strong>");
            result = result.replace("**", "</strong>");
            resultsList += `<li>${result}</li>`;
        });
      } 
      console.log(resultsList);
      
      let chatContent = `<h4><strong>Chart</strong></br> ${response.chart_name}(${response.chart_id})</h4>` +
                        `<h4><strong>URL</strong></br> ${response.chart_url}</h4>` +
                        `<h4><strong>Results</strong></h4>` +
                        `<ul id="results-list">${resultsList}</ul>`;
      let chatData = {
        user: game.userId,
        speaker: ChatMessage.getSpeaker(),
        content: chatContent,
        whisper
      };

      ChatMessage.create(chatData, {});
    } else {
      // We reached our target server, but it returned an error
      console.log("Server error.");
    }
  };

  request.onerror = function() {
    // There was a connection error of some sort
    console.log("Error getting result.");
  };

  request.send();
} 

roll(chartId);
```

**Comment by mattstjean** [comment]
I can make a PR later when I have time but @tbrockwood I ran into this issue and fixed it locally. It doesn't look like an issue with the Foundry update but rather that Chartopia broke their API contract and rewrote the endpoint. I quickly added some styling to make it look a bit nicer in foundry.

![image](https://user-images.githubusercontent.com/18298494/194137122-f9896e83-ef84-4169-bcd2-d71f3164eaef.png)


/**
 * Make a roll from chartopia and output the results in the chat window.
 * If you find yourself using this macro often, please support chartopia on patreon.
 */

// chart id from url. IE 19449 is the chart id in https://chartopia.d12dev.com/chart/19449/
const chartId = 61778;
// only let the gm see the results. false = everyone sees in chat. true = gm whispered results.
const gmOnly = false;


//////////////////////////////////
/// Don't edit past this point ///
//////////////////////////////////

const requestUrl = `https://chartopia.d12dev.com/api/charts/${chartId}/roll/`;


function roll(id) {
  let request = new XMLHttpRequest();
  request.open('POST', requestUrl, true);

  request.onload = function() {
    if (request.status >= 200 && request.status < 400) {
      // Success!
      let whisper = !!gmOnly ? game.users.map(u => {
          if (u.isGM) return u.id;
      }) : [];
      console.log('whisper', whisper);
      // Create chat content.
      const response = JSON.parse(request.response);
      let resultsList = ``;
      if (Array.isArray(response.results)) {
        response.results.forEach(result => {
            result = result.replace("**", "<strong>");
            result = result.replace("**", "</strong>");
            resultsList += `<li>${result}</li>`;
        });
      } 
      console.log(resultsList);
      
      let chatContent = `<h4><strong>Chart</strong></br> ${response.chart_name}(${response.chart_id})</h4>` +
                        `<h4><strong>URL</strong></br> ${response.chart_url}</h4>` +
                        `<h4><strong>Results</strong></h4>` +
                        `<ul id="results-list">${resultsList}</ul>`;
      let chatData = {
        user: game.userId,
        speaker: ChatMessage.getSpeaker(),
        content: chatContent,
        whisper
      };

      ChatMessage.create(chatData, {});
    } else {
      // We reached our target server, but it returned an error
      console.log("Server error.");
    }
  };

  request.onerror = function() {
    // There was a connection error of some sort
    console.log("Error getting result.");
  };

  request.send();
} 

roll(chartId);

**Comment by tbrockwood** [comment]
Thanks!

**Comment by AnthonyVadala** [comment]
Updated in v9.19
