### ISSUE TITLE
Label system specific macros as such

### ISSUE THREAD

**Issue by meditatingCybermind** [foundry-vtt-community/macros#76]
I think it would be helpful for things like "Rage" to instead be called "Rage (5e)" so games with similar concepts wouldn't have name collisions.

**Comment by AnthonyVadala** [comment]
This is a good suggestion! But I actually already had something else in mind. I am currently waiting for the folder organization within Compendium Packs feature to be added to Foundry. Once that Feature is added I will be adding game system specific folders in each pack to help with organization.

You can track progress of that feature request here: https://gitlab.com/foundrynet/foundryvtt/-/issues/1109

**Comment by AnthonyVadala** [comment]
Honestly we probably should just drop the 5e stuff in their own directory

_Originally posted by @shawndibble in https://github.com/foundry-vtt-community/macros/pull/79#issuecomment-651324846_

**Comment by AnthonyVadala** [comment]
@shawndibble Hmm, would it be worth making system specific folders for each kind of macro function while folder organization within Compendium Packs is being added or prepending the system to a macro that it is used in?

Ex. `5e_actor/` for the temporary folder solution
Ex. `5e_name_of_macro` for temporary prepending

**Comment by shawndibble** [comment]
I think the number of compendiums in foundry is too high as it is now, however I also feel like we need some kind of distinction with the modules. Either pre-prending the macro names with the sytem or maybe consolidating to 3 folders would be better.

IE: 
modules required, 5e, generic/system agnostic
OR how you have them `5e_name_of_module`.

I definitely think we should drop the current separation as roll/actor/items/tokens/misc macros tend to do stuff that would cause them to fall into multiple folders. In either case, I think macros that require certain modules to be installed, should be their own folder.

**Comment by FlanFlanSu** [comment]
Given that this is a continuous effort, and foundry will only continue to grow in terms of its community and playable systems, the most elegant way would be to define system-specific content packs.

Here's an example:

![grafik](https://user-images.githubusercontent.com/45763370/87562996-039e9880-c6bf-11ea-882b-b6227eb27391.png)

This will both allow blacklisting macros that won't be relevant to the system (thus removing content clutter) as well as keep the module scalable to as many systems that are still coming around and establish themselves.

**Comment by shawndibble** [comment]
I created a PR that fixes several broken macros. It also implements something similar to this in that we now have 5e and PF1e directories.
